# Set up client, imports, and vars

In [1]:
import os
from supabase import create_client, Client
from supabase.client import ClientOptions
from dotenv import load_dotenv
import pandas as pd

load_dotenv()

supabase: Client = create_client(
    os.environ.get("SUPABASE_URL"),
    os.environ.get("SUPABASE_KEY")
)

In [2]:
DAY_AHEAD_MARKET_ZONAL_LBMP = "Day-Ahead_Market_Zonal_LBMP"
DAY_AHEAD_MARKET_ISO_LOAD_FORECAST = "Day_Ahead_Market_ISO_Load_Forecast"
REAL_TIME_COMMITMENT_ZONAL_LBMP = "Real_Time_Commitment_Zonal_LBMP."
REAL_TIME_DISPATCH_ACTUAL_LOAD_NYC = "Real_Time_Dispatch_Actual_Load_NYC"
REAL_TIME_DISPATCH_ZONAL_LBMP = "Real_Time_Dispatch_Zonal_LBMP"
REAL_TIME_WEIGHTED_INTEGRATED_ACTUAL_LOAD = "Real_Time_Weighted_Integrated_Actual_Load"
REAL_TIME_WEIGHTED_INTEGRATED_ZONAL_LBMP = "Real_Time_Weighted_Integrated_Zonal_LBMP"

DA_LOAD_MEASUREMENTS = "da_load_measurements"
RT_LOAD_MEASUREMENTS = "rt_load_measurements"
PRICES_MEASUREMENTS = "prices_measurements"
DATASETS = "datasets"
LOCATIONS = "locations"

# Verify data observability

In [14]:

da_load = pd.DataFrame(supabase.table(DA_LOAD_MEASUREMENTS).select("*").execute().data)
rt_load = pd.DataFrame(supabase.table(RT_LOAD_MEASUREMENTS).select("*").execute().data)
prices = pd.DataFrame(supabase.table(PRICES_MEASUREMENTS).select("*").execute().data)
datasets = pd.DataFrame(supabase.table(DATASETS).select("*").execute().data)
locations = pd.DataFrame(supabase.table(LOCATIONS).select("*").execute().data)
print(f"Verify data existence with shape: \nda_load: {da_load.shape} \nrt_load: {rt_load.shape} \nprices: {prices.shape} \ndatasets: {datasets.shape} \nlocations: {locations.shape} \n**Supabase returns a max of 10,000 rows**")

Verify data existence with shape:
da_load: (7920, 7)
rt_load: (9556, 6)
prices: (10000, 9)
datasets: (7, 7)
locations: (1, 4)
**Supabase returns a max of 10,000 rows**

In [15]:
unique_zones_df = pd.DataFrame(locations["zone_name"].unique(), columns=["zone_name"])
unique_zones_df

  zone_name
0    N.Y.C.

In [21]:
unique_datasets = datasets[["dataset_name", "market"]].drop_duplicates().reset_index(drop=True)
unique_datasets

                                      dataset_name   market
0         OASIS_Day_Ahead_Market_ISO_Load_Forecast     load
1                OASIS_Day-Ahead_Market_Zonal_LBMP  pricing
2   OASIS_Real_Time_Weighted_Integrated_Zonal_LBMP  pricing
3  OASIS_Real_Time_Weighted_Integrated_Actual_Load     load
4            OASIS_Real_Time_Commitment_Zonal_LBMP  pricing
5              OASIS_Real_Time_Dispatch_Zonal_LBMP  pricing
6         OASIS_Real_Time_Dispatch_Actual_Load_NYC     load